<a href="https://colab.research.google.com/github/Raghavendarlokineni/colab-machine-learning/blob/develop/tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Tensors**

In [0]:
import tensorflow as tf
%tensorflow_version 2.x

tensor_int = tf.Variable(100)
print(tensor_int)

tensor_int2 = tf.Variable(200, dtype=tf.int64)
print(tensor_int2)

tensor_int3 = tf.Variable(300, tf.int16)
print(tensor_int3)

tensor2 = tf.Variable(15.0)
print(tensor2)

tensor3 = tf.Variable(25.0, dtype=tf.float16)
print(tensor3)

tensor4 = tf.Variable(35.00000000000001, dtype=tf.float64)
print(tensor4)

tensor_string = tf.Variable("hello", dtype=tf.string)
print(tensor_string)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>
<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=200>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=300>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=15.0>
<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>
<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=35.00000000000001>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello'>


**Rank/Degree of a Tensor**




```
### Defines number of dimensions involved in the tensor

Rank is also known as Degree, order, ndims
```




In [0]:
tensor1 = tf.Variable([1])
print(tf.rank(tensor1))

tensor2 = tf.Variable([1,2,3])
print(tf.rank(tensor2))

tensor3 = tf.Variable([[1],
                       [2],
                       [3]])
print(tf.rank(tensor3))

tensor4 = tf.Variable([[1,1],
                       [2,2],
                       [3,3]])
print(tf.rank(tensor4))

tensor5 = tf.Variable([
                       [[3,3],[1,1]],
                       [[1,1],[2,2]],
                       [[2,2],[3,3]]
                       ])
print(tf.rank(tensor5))


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


**Shape of Tensors**



```
### number of elements exists in each dimension(rank)
```



In [0]:
#lets find out shape for above tensors

print(tensor1.shape)
print(tensor2.shape)
print(tensor3.shape)
print(tensor4.shape)
print(tensor5.shape)

(1,)
(3,)
(3, 1)
(3, 2)
(3, 2, 2)


**Changing Shape of a Tensor**



```
# Number of elements of a tensor is the product of sizes of all shapes, so tensor5.shape = (3,2,2). 
So the number of elements of this tensor are 12. 

```

Below examples are to demonstrate reshaping of tensors


In [0]:
#create a tensor with shape(1,2,3) with all ones, either of this are same (1,2,3) or [1,2,3]
tensor1 = tf.ones([1,2,3])
print("TENSOR 1 shape is {1} \n {0}\n ".format(tensor1, tensor1.shape))

#reshape abover tensor with shape(3,2,1)
tensor2= tf.reshape(tensor1, (3,2,1))
print("TENSOR 2 shape is {1} \n {0}\n ".format(tensor2, tensor2.shape))

#reshaping in a different way, -1 indicates tensorflow will calculate the size of the dimension by itself with 3. 
tensor3 = tf.reshape(tensor1,(3,-1))
print("TENSOR 3 shape is {1} \n {0}\n ".format(tensor3, tensor3.shape))


TENSOR 1 shape is (1, 2, 3) 
 [[[1. 1. 1.]
  [1. 1. 1.]]]
 
TENSOR 2 shape is (3, 2, 1) 
 [[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]
 
TENSOR 3 shape is (3, 2) 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


**Slicing tensors**

This is similar to slicing in python

In [0]:
list_2d = [[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]
]
tensor_2d = tf.Variable(list_2d)

print(tensor_2d.shape)
print(tf.rank(tensor_2d))

(3, 4)
tf.Tensor(2, shape=(), dtype=int32)
